spring.application.name=backend
server.port=8080

spring.datasource.url=jdbc:sqlserver://34.238.193.242:1433;databaseName=proyecto_db;encrypt=false
spring.datasource.username=sa
spring.datasource.password=TuPassword123!

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect